"""
The audit pack: a workspace's requirement → control → evidence chain as XLSX.

Only the caller's workspace rows and the library documents it can see.
Every cell is written as text, and text that a spreadsheet could read as a
formula (= + - @, tab, carriage return) is prefixed with an apostrophe, so
nothing in the workbook can execute.
"""

from __future__ import annotations

from datetime import datetime
from io import BytesIO

from models.compliance_graph import GraphEvent, Impact, Link
from services.compliance_graph import applicability, core, queries, taxonomy
from services.compliance_graph.common import LAGOS
from services.compliance_graph.visibility import Scope

FORMULA_LEADS = ("=", "+", "-", "@", "\t", "\r")
DISCLAIMER = ("This workbook lists what Iroko's records show. A gap means the item is not established in "
              "Iroko's records; it is not a compliance finding. Suggestions by Iroko are listed as suggestions "
              "until a reviewer confirmed them.")


def safe(value) -> str:
    text = "" if value is None else str(value)
    if text.startswith(FORMULA_LEADS):
        text = "'" + text
    return text


def _row(sheet, values):
    from openpyxl.cell import WriteOnlyCell

    cells = []
    for value in values:
        cell = WriteOnlyCell(sheet, value=safe(value))
        cell.data_type = "s"
        cells.append(cell)
    sheet.append(cells)


def build(db, scope: Scope, *, generated_by: str | None) -> bytes:
    from openpyxl import Workbook

    rows = queries.requirement_rows(db, scope)
    profile = core.profile(db, scope.workspace_id)
    controls = {c["id"]: c for c in queries.controls_list(db, scope, include_retired=True)}
    links = core.workspace_links(db, scope)
    people = queries.names(db, [link.reviewed_by for link in links])
    by_lineage, evidence_by_control, evidence_by_lineage = {}, {}, {}
    for link in links:
        if link.review_status == "rejected":
            continue
        if link.relation == "addresses":
            by_lineage.setdefault(link.to_id, []).append(link)
        elif link.relation == "evidences" and link.to_type == "control":
            evidence_by_control.setdefault(link.to_id, []).append(link)
        elif link.relation == "evidences":
            evidence_by_lineage.setdefault(link.to_id, []).append(link)
    titles = core.document_titles(db, [link.from_id for link in links if link.relation == "evidences"])

    wb = Workbook(write_only=True)
    about = wb.create_sheet("About")
    _row(about, ["Iroko compliance audit pack"])
    _row(about, ["Generated", datetime.now(LAGOS).strftime("%Y-%m-%d %H:%M WAT")])
    _row(about, ["Generated by", generated_by or ""])
    _row(about, ["Licence categories", ", ".join(taxonomy.label(c) for c in profile["category_codes"]) or "Not set"])
    _row(about, ["Note", DISCLAIMER])

    trace = wb.create_sheet("Traceability")
    _row(trace, ["Requirement (Iroko's summary)", "Requirement (exact words)", "Instrument", "Reference", "Regulator",
                 "Page", "Published", "Effective", "Applicability", "Control", "Control status", "Control owner",
                 "Link status", "Evidence record", "Evidence period", "Evidence status", "Coverage", "Owner",
                 "Next due"])
    for r in rows:
        if r["applicability"]["state"] not in applicability.APPLYING_STATES:
            continue
        doc = r["document"]
        base = [r["summary"], r["quote"], doc.get("title"), doc.get("reference"), doc.get("regulator"),
                r["page_number"], doc.get("published_date"), doc.get("effective_date"), r["applicability"]["label"]]
        tail = [r["coverage"]["label"], r["owner"]["name"] or r["owner"]["team"], r["due"]["date"] or r["due"]["description"]]
        chain = by_lineage.get(r["lineage_id"], [])
        direct = evidence_by_lineage.get(r["lineage_id"], [])
        if not chain and not direct:
            _row(trace, base + ["", "", "", "", "", "", ""] + tail)
            continue
        for link in chain:
            control = controls.get(link.from_id) or {}
            status = queries.status_payload(link, people)["label"]
            evidences = evidence_by_control.get(link.from_id, []) or [None]
            for ev in evidences:
                _row(trace, base + [
                    control.get("name"), (control.get("review") or {}).get("label"),
                    (control.get("owner") or {}).get("name") or (control.get("owner") or {}).get("team"), status,
                    titles.get(ev.from_id) if ev else "",
                    _period(ev) if ev else "", queries.status_payload(ev, people)["label"] if ev else "",
                ] + tail)
        for ev in direct:
            _row(trace, base + ["", "", "", "", titles.get(ev.from_id), _period(ev),
                                queries.status_payload(ev, people)["label"]] + tail)

    gaps = wb.create_sheet("Gaps")
    _row(gaps, ["Requirement", "Instrument", "Coverage", "Owner"])
    for r in rows:
        if r["applicability"]["state"] in applicability.APPLYING_STATES and r["coverage"]["state"] in (
                "no_control_linked", "control_confirmed_no_evidence", "evidence_out_of_date"):
            _row(gaps, [r["summary"] or r["quote"], r["document"].get("title"), r["coverage"]["label"],
                        r["owner"]["name"] or r["owner"]["team"]])

    changes = wb.create_sheet("Changes")
    _row(changes, ["Date", "Change", "Status", "Links flagged for re-review"])
    for impact in (db.query(Impact).filter(Impact.workspace_id == scope.workspace_id)
                   .order_by(Impact.created_at.desc()).limit(500)):
        _row(changes, [impact.created_at.date().isoformat() if impact.created_at else "", impact.summary, impact.status,
                       len((impact.affected or {}).get("flagged", []))])

    log = wb.create_sheet("Review history")
    _row(log, ["When (UTC)", "Item", "Action", "From", "To", "By", "Note"])
    events = (db.query(GraphEvent).filter(GraphEvent.workspace_id == scope.workspace_id)
              .order_by(GraphEvent.created_at.desc()).limit(5000).all())
    actors = queries.names(db, [e.actor_user_id for e in events])
    for e in events:
        _row(log, [e.created_at.isoformat(timespec="seconds") if e.created_at else "", f"{e.subject_type} {e.subject_id}",
                   e.action, e.from_status, e.to_status, actors.get(e.actor_user_id) or ("Iroko" if not e.actor_user_id else ""),
                   e.note])
    stream = BytesIO()
    wb.save(stream)
    return stream.getvalue()


def _period(link: Link | None) -> str:
    attributes = (link.attributes or {}) if link else {}
    start, end = attributes.get("period_start"), attributes.get("period_end")
    if start and end and start != end:
        return f"{start} to {end}"
    return start or end or attributes.get("record_date") or ""
