"use client";

import Link from "next/link";
import Image from "next/image";
import { useState } from "react";
import s from "./homepage.module.css";

const PILOT = "Request Free 30-Day Pilot";
const agents = [
  { id: "researcher", name: "Researcher", tag: "Find the evidence", title: "Your documents.\nClear answers.", description: "Ask a question in plain English. Researcher connects the dots across your policies, circulars, and internal documents, with source references your team can check.", points: ["Search across your document library", "Follow each answer back to its source"], visual: "research" },
  { id: "watchdog", name: "Watchdog", tag: "Stay one step ahead", title: "See what needs\nyour attention.", description: "Keep regulatory requirements and operational thresholds in view. Watchdog flags changes and emerging issues so your team can focus on what needs action.", points: ["Monitor compliance indicators", "Bring important changes into one view"], visual: "radar" },
  { id: "analyst", name: "Analyst", tag: "Make sense of the numbers", title: "Turn information\ninto understanding.", description: "Bring scattered figures and findings into a clearer picture. Analyst helps your team explore trends, compare evidence, and understand what is changing across the business.", points: ["Surface patterns across your documents", "Explore the evidence behind an insight"], visual: "chart" },
  { id: "sentinel", name: "Sentinel", tag: "Look closer at risk", title: "Spot the signals\nthat deserve a second look.", description: "Give your team a starting point for investigating suspicious activity. Sentinel surfaces potential fraud and AML/CFT concerns, with context to support a human review.", points: ["Bring risk signals to the surface", "Review findings with supporting context"], visual: "shield" },
  { id: "strategist", name: "Strategist", tag: "Move from insight to action", title: "Know what to\ndo next.", description: "Pull research, monitoring, and analysis into a practical next step. Strategist helps your team weigh the evidence and prepare recommendations for the people making the decision.", points: ["Connect findings across the five agents", "Turn evidence into a plan your team can review"], visual: "steps" },
] as const;

const questions = [
  ["Which regulators and requirements does Iroko cover?", "Iroko’s financial-services configuration supports work with CBN and SEC regulatory material, AML/CFT requirements, and NDPA-related data-protection workflows. During onboarding, we agree the sources and requirements relevant to your licence and operations. Your team remains responsible for reviewing decisions and submissions."],
  ["How does the free 30-day pilot work?", "Request your pilot and book a 30-minute onboarding call. We use that call to understand your priorities and agree what to explore with your team. Your free 30-day pilot starts from the onboarding call. No payment details are needed to request it."],
  ["What does it cost after the pilot?", "Our current Growth plan starts at ₦350,000 per month and Pro at ₦750,000 per month. Enterprise engagements are quoted around your document volume, integrations, and deployment needs. We’ll discuss the right scope with you before you decide to continue."],
  ["How is our data handled?", "Iroko uses access controls to manage who can work with your organisation’s documents, and audit records help trace activity and decisions. During onboarding, we’ll confirm your deployment, storage, retention, and access requirements before agreeing which data to connect."],
  ["Can our team review the answers?", "Yes. Iroko is designed to support your team’s judgement. Referenced answers help you inspect the underlying documents, while the audit trail records the evidence and activity behind decisions."],
];

function Arrow({ diagonal = false }: { diagonal?: boolean }) { return <span aria-hidden="true">{diagonal ? "↗" : "→"}</span>; }
function PilotLink({ className = "" }: { className?: string }) { return <Link href="/request-demo" className={`${s.button} ${className}`}>{PILOT}<Arrow /></Link>; }
function Brand() { return <Link href="/" className={s.brand} aria-label="Iroko AI home"><svg viewBox="0 0 32 36" width="30" height="34" aria-hidden="true"><path d="M16 1 30 9v17l-14 9L2 26V9Z" fill="#176b49" /><path d="m16 9 7 4v9l-7 4-7-4v-9Z" fill="none" stroke="currentColor" strokeWidth="2" /><circle cx="16" cy="17.5" r="3" fill="currentColor" /></svg><span>iroko<span className={s.brandAi}>ai</span></span></Link>; }

function AgentVisual({ kind }: { kind: typeof agents[number]["visual"] }) {
  return <div className={`${s.visual} ${s[kind]}`} aria-hidden="true">
    <div className={s.visualGrid} />
    {kind === "research" && <><div className={s.paperBack} /><div className={s.paper}><span className={s.miniLabel}>RESEARCHER / DOCUMENT INTELLIGENCE</span><h4>From a question<br />to the evidence.</h4><div className={s.question}>What does our policy say?</div><div className={s.textLines}><i /><i /><i /></div><div className={s.sourceChip}>↗ &nbsp; Source document · Policy library</div></div><div className={s.floatingBadge}>✓ &nbsp; Answers with references</div></>}
    {kind === "radar" && <><div className={s.radarDisc}><div /><div /><div /><i /><b /><em /></div><div className={s.radarCard}><span className={s.statusDot} /><div><strong>Keep the important things in view.</strong><small>Monitor · Flag · Review</small></div></div></>}
    {kind === "chart" && <><div className={s.chartCard}><div className={s.chartHeading}><span>See the bigger picture</span><small>ANALYST</small></div><div className={s.chart}><div className={s.chartLines} /><svg viewBox="0 0 400 150" preserveAspectRatio="none"><path d="M0 140 45 110 90 120 145 72 190 89 250 43 295 58 350 25 400 8V150H0Z" fill="#d7eee0" /><path d="M0 140 45 110 90 120 145 72 190 89 250 43 295 58 350 25 400 8" fill="none" stroke="#29815a" strokeWidth="3" /></svg></div><div className={s.chartLegend}><span>● &nbsp; Evidence</span><span>● &nbsp; Trends</span><span>● &nbsp; Context</span></div></div><div className={s.floatingBadge}>↗ &nbsp; Connect the dots</div></>}
    {kind === "shield" && <><div className={s.shieldOrbit} /><svg className={s.shieldSvg} viewBox="0 0 200 230"><path d="m100 12 80 30v66c0 53-46 87-80 108-34-21-80-55-80-108V42Z" fill="#b8d6b2" /><path d="m100 39 56 21v48c0 35-30 64-56 81-26-17-56-46-56-81V60Z" fill="#e6f3e9" /><path d="m75 109 18 18 35-40" stroke="#38704a" strokeWidth="6" fill="none" strokeLinecap="round" strokeLinejoin="round" /></svg><div className={s.riskCard}><span>!</span><div><strong>A signal. A closer look.</strong><small>Evidence for your review</small></div></div></>}
    {kind === "steps" && <><Image src="/marketing/team-collaboration.jpg" alt="Colleagues working together around a laptop" fill sizes="(max-width: 600px) 100vw, 500px" className={s.teamPhoto} /><div className={s.photoCaption}><strong>Better decisions start with your team.</strong><span>A guided pilot, built around your priorities.</span></div></>}
    {kind !== "steps" && <span className={s.visualCaption}>Concept illustration</span>}
  </div>;
}

export default function HomePage() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <div className={s.page}>
    <a className={s.skip} href="#main">Skip to content</a>
    <header className={s.header}><div className={s.navWrap}>
      <Brand />
      <nav aria-label="Main navigation" className={s.desktopNav}><a href="#platform">Platform</a><a href="#who-its-for">Who it’s for</a><a href="#audit-trail">Trust & traceability</a><a href="#questions">FAQs</a></nav>
      <div className={s.navActions}><Link href="/login" className={s.signIn}>Sign in</Link><PilotLink /><button className={s.menuToggle} aria-label={menuOpen ? "Close navigation" : "Open navigation"} aria-expanded={menuOpen} aria-controls="mobile-navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? "✕" : "☰"}</button></div>
    </div>{menuOpen && <nav id="mobile-navigation" aria-label="Mobile navigation" className={s.mobileNav} onClick={() => setMenuOpen(false)}><a href="#platform">Platform</a><a href="#who-its-for">Who it’s for</a><a href="#audit-trail">Trust & traceability</a><a href="#questions">FAQs</a><Link href="/login">Sign in</Link><PilotLink /></nav>}</header>

    <main id="main">
      <section className={s.hero}><div className={`${s.container} ${s.heroGrid}`}>
        <div className={s.heroCopy}><p className={s.eyebrow}><span /> BUILT FOR NIGERIAN FINANCIAL SERVICES</p><h1>Clear compliance.<br />For MFBs.<br /><span>For fintechs.</span></h1><p className={s.heroDescription}>Iroko AI turns your MFB or fintech’s documents into clear compliance answers, early warnings, and practical next steps.</p><div className={s.heroActions}><PilotLink /><a href="#platform" className={s.textLink}><span className={s.play}>▶</span>See how it works</a></div><p className={s.heroNote}>30 days. Your documents. A clearer way to work.</p></div>
        <div className={s.heroArt} aria-label="Illustration of Iroko’s five agents bringing documents and evidence together"><div className={s.orbit} /><div className={s.orbitTwo} /><div className={s.heroGlow} /><div className={s.documentOne}><span>YOUR DOCUMENTS</span><i /><i /><i /></div><div className={s.documentTwo}><span>THE EVIDENCE</span><i /><i /><i /></div><div className={s.core}><svg viewBox="0 0 80 86" aria-hidden="true"><path d="m40 4 33 19v40L40 82 7 63V23Z" fill="none" stroke="currentColor" strokeWidth="3"/><path d="m40 22 17 10v22L40 64 23 54V32Z" fill="none" stroke="currentColor" strokeWidth="3"/><circle cx="40" cy="43" r="7" fill="currentColor"/></svg><strong>iroko ai</strong><span>Clarity, connected.</span></div><div className={s.agentPill}>✧ &nbsp; Researcher</div><div className={s.agentPill}>◉ &nbsp; Watchdog</div><div className={s.agentPill}>▥ &nbsp; Analyst</div><div className={s.agentPill}>◇ &nbsp; Sentinel</div><div className={s.agentPill}>↗ &nbsp; Strategist</div><div className={s.heroResult}><span>✓</span><div><strong>From information to action.</strong><small>Five agents. One connected view.</small></div></div></div>
      </div></section>

      <section className={s.trust} aria-label="Iroko’s ecosystem"><div className={s.container}><p className={s.trustIntro}>Building within Nigeria’s technology ecosystem</p><div className={s.trustMarks}><div><strong className={s.mtn}>MTN</strong><span>Enterprise engagement</span></div><div><strong className={s.threeMtt}>3MTT<span>◆</span></strong><span>Technical talent ecosystem</span></div><div><strong className={s.smedan}>SMEDAN<span>▰</span></strong><span>Registered business</span></div><div><strong className={s.microsoft}><i><b /><b /><b /><b /></i>Microsoft</strong><span>Technology ecosystem</span></div></div></div></section>

      <section id="platform" className={s.platformIntro}><div className={s.container}><p className={s.eyebrow}>MEET YOUR INTELLIGENCE TEAM</p><h2>Five specialists.<br />One less thing to worry about.</h2><p>From the first question to the next decision, your agents work together<br className={s.desktopBreak} /> to make your organisation’s knowledge useful.</p><div className={s.agentIndex}>{agents.map((agent, i) => <a key={agent.id} href={`#${agent.id}`}><span>0{i + 1}</span>{agent.name}<Arrow diagonal /></a>)}</div></div></section>

      {agents.map((agent, i) => <section id={agent.id} key={agent.id} className={`${s.feature} ${i % 2 === 1 ? s.tinted : ""}`}><div className={`${s.container} ${s.featureGrid} ${i % 2 === 0 ? s.visualFirst : ""}`}><div className={s.featureCopy}><p className={s.eyebrow}><span className={s.agentNumber}>0{i + 1}</span>{agent.name.toUpperCase()} / {agent.tag.toUpperCase()}</p><h2>{agent.title}</h2><p>{agent.description}</p><ul>{agent.points.map(point => <li key={point}><span>✓</span>{point}</li>)}</ul><Link href="/request-demo" className={s.textLink}>Explore it with your team <Arrow /></Link></div><AgentVisual kind={agent.visual} /></div></section>)}

      <section id="audit-trail" className={s.highlight}><div className={`${s.container} ${s.highlightGrid}`}><div><p className={s.eyebrow}>A RECORD YOU CAN FOLLOW</p><h2>Every decision<br />has a backstory.<br /><span>Keep yours intact.</span></h2><p>Iroko’s hash-chained audit trail links each record to the one before it. That makes changes detectable and gives your team a way to follow the evidence behind a decision.</p><a href="#questions" className={s.darkLink}>Built for review. Ready for questions. <Arrow /></a></div><div className={s.auditVisual}><div className={s.auditTop}><span>THE AUDIT TRAIL</span><span>↗ Traceable by design</span></div>{[{n:"01",title:"The evidence",text:"A document enters the record.",hash:"8f2a · c091"},{n:"02",title:"The reasoning",text:"A finding connects to its source.",hash:"c091 · 7be4"},{n:"03",title:"The decision",text:"An action links back to the evidence.",hash:"7be4 · a630"}].map(step=><div key={step.n} className={s.auditStep}><span>{step.n}</span><div><h3>{step.title}</h3><p>{step.text}</p><code>{step.hash}</code></div><b aria-hidden="true">↗</b></div>)}<small>Illustration of linked audit records</small></div></div></section>

      <section id="who-its-for" className={s.audience}><div className={s.container}><p className={s.eyebrow}>BUILT AROUND YOUR WORLD</p><h2>Different teams.<br />The same need for clarity.</h2><div className={s.audienceCards}>{[{name:"Microfinance Banks",icon:"▤",text:"Bring policies, prudential requirements, and everyday compliance questions into focus."},{name:"Fintechs",icon:"⌘",text:"Keep pace with regulatory change while your products and operations grow."},{name:"Enterprise",icon:"▥",text:"Connect knowledge across departments and turn scattered documents into useful answers."}].map((item,i)=><article key={item.name}><span className={s.audienceIcon}>{item.icon}</span><small>IROKO FOR</small><h3>{item.name}</h3><p>{item.text}</p><Link href="/request-demo">Let’s talk about your team <Arrow diagonal /></Link><span className={s.cardNumber}>0{i+1}</span></article>)}</div></div></section>

      <section id="questions" className={s.faq}><div className={`${s.container} ${s.faqGrid}`}><div><p className={s.eyebrow}>GOOD QUESTIONS. CLEAR ANSWERS.</p><h2>A little more<br />about Iroko.</h2><p>Thinking about a pilot?<br />Here’s a good place to start.</p><a className={s.textLink} href="mailto:ekeh@irokoai.site">Talk to our team <Arrow /></a></div><div>{questions.map(([question,answer])=><details key={question} className={s.faqItem}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></div></section>

      <section className={s.finalCta}><div className={`${s.container} ${s.finalGrid}`}><div><p className={s.eyebrow}>YOUR NEXT CHAPTER STARTS HERE</p><h2>See what clarity looks like.<br />With your own documents.</h2><p>Start your free 30-day pilot with a guided onboarding call.</p></div><div><PilotLink /><span>Free for 30 days · No payment details needed</span></div></div></section>
    </main>

    <footer id="contact" className={s.footer}><div className={s.container}><div className={s.footerGrid}><div className={s.footerBrand}><Brand /><p>Intelligence for the decisions<br />that matter.</p></div><div><h3>Product</h3><a href="#platform">The platform</a><a href="#researcher">Our five agents</a><a href="#audit-trail">Audit trail</a><Link href="/request-demo">Free pilot</Link></div><div><h3>Company</h3><a href="#who-its-for">Who we’re for</a><a href="#contact">Contact us</a><a href="https://www.linkedin.com/company/irokoai" target="_blank" rel="noopener noreferrer">LinkedIn <Arrow diagonal /></a><a href="https://github.com/Nd-Web/Iroko-x-Atlas" target="_blank" rel="noopener noreferrer">GitHub <Arrow diagonal /></a></div><div><h3>Support</h3><a href="#questions">Common questions</a><a href="#questions">Pricing & plans</a><Link href="/login">Sign in</Link><a href="mailto:ekeh@irokoai.site">Get in touch</a></div><div><h3>Contact</h3><address>7, Adeosun St, Ojo,<br />Lagos, Nigeria</address><a href="mailto:ekeh@irokoai.site">ekeh@irokoai.site <Arrow diagonal /></a></div></div><div className={s.footerBottom}><span>© {new Date().getFullYear()} Iroko AI. All rights reserved.</span><span>Built in Nigeria. Designed for clarity.</span><a href="#main">Back to top ↑</a></div></div></footer>
  </div>;
}
