"""
models/message.py — Async SQLAlchemy model for individual chat messages.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime

from sqlalchemy import Column, DateTime, Enum, Float, ForeignKey, JSON, String, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from services.database import Base


# ─── Enum ─────────────────────────────────────────────────────────────────────


class MessageRole(str, enum.Enum):
    user = "user"
    assistant = "assistant"


# ─── Model ────────────────────────────────────────────────────────────────────


class MessageAsync(Base):
    """
    A single turn in a conversation — either from the user or the assistant.

    Attributes
    ----------
    id : str (UUID)
        Primary key.
    conversation_id : str (UUID)
        FK to ``conversations_v2.id``.
    role : MessageRole
        ``user`` | ``assistant``.
    content : str
        Full text content of the message.
    reasoning_steps : list[dict] | None
        Serialised agent reasoning chain (list of step dicts).
        Only populated for assistant messages generated by the orchestrator.
    risk_score : float | None
        0–10 risk assessment attached to the assistant's response.
    created_at : datetime
        UTC creation timestamp.
    """

    __tablename__ = "messages_v2"

    id = Column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        nullable=False,
    )
    conversation_id = Column(
        String(36),
        ForeignKey("conversations_v2.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    role = Column(
        Enum(MessageRole, name="messagerole_async", create_constraint=True),
        nullable=False,
    )
    content = Column(Text, nullable=False)
    reasoning_steps = Column(JSON, nullable=True)
    risk_score = Column(Float, nullable=True)
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=datetime.utcnow,
    )

    # ── Relationships ──────────────────────────────────────────────────────────

    conversation = relationship("ConversationAsync", back_populates="messages")

    def __repr__(self) -> str:  # pragma: no cover
        preview = (self.content or "")[:40].replace("\n", " ")
        return f"<Message id={self.id!r} role={self.role} content={preview!r}>"
